[project]
name = "deep-learning"
version = "0.1.0"
description = "Experimentating various deep learning skills"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arxiv>=2.2.0",
    "mcp>=1.9.1",
    "nest-asyncio>=1.6.0",
    "openai>=1.82.0",
]
